name: Deploy NestJS API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
      runs-on: ubuntu-latest
      environment: WeatherKids_PROD
      steps:
          - name: Pull changes into server
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.DROPLET_SSH_HOST }}
              username: ${{ secrets.DROPLET_SSH_USERNAME }}
              key: ${{ secrets.DROPLET_SSH_KEY }}
              script: |
                git clone https://github.com/gaveshalabs/weatherkids-data-api.git
                cp .env.prod weatherkids-data-api/.env.prod
                cd weatherkids-data-api
                npm ci --only=production
                npm run build
                node dist/index.js
                echo 'Deployment Done!'
