name: Deploy NestJS API to DigitalOcean

on:
    push:
        branches:
            - main

env:
    DOCKER_SERVICE_NAME: unknown
    DOCKER_REPO: unknown

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout files
              uses: actions/checkout@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                passsword: ${{ secrets.DOCKERHUB_PASSWORD }}
            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                push: true
                tags: ${{ env.DOCKER_REPO }}

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Updating docker image
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.DROPLET_SSH_HOST }}
                username: ${{ secrets.DROPLET_SSH_USERNAME }}
                key: ${{ secrets.DROPLET_SSH_KEY }}
                script: |
                    docker service update --image "${{ env.DOCKER_REPO }}:latest" ${{ env.DOCKER_SERVICE_NAME }}
