name: Deploy NestJS API to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
      runs-on: ubuntu-latest
      environment: WeatherKids_PROD
      steps:
          - name: Pull changes into server
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.DROPLET_SSH_HOST }}
              username: ${{ secrets.DROPLET_SSH_USERNAME }}
              key: ${{ secrets.DROPLET_SSH_KEY }}
              script: |
                # Variables
                REPO_URL="https://github.com/gaveshalabs/weatherkids-data-api"
                TARGET_DIR="weatherkids-data-api"
                
                # Check if the target directory exists
                if [ -d "$TARGET_DIR" ]; then
                  echo "Directory $TARGET_DIR exists. Performing git pull."
                  cd "$TARGET_DIR"
                  git pull
                else
                  echo "Directory $TARGET_DIR does not exist. Cloning repository."
                  git clone "$REPO_URL" "$TARGET_DIR"
                  cp .env.prod "$TARGET_DIR/.env.prod"
                  cd "$TARGET_DIR"
                fi
                nvm use 20
                npm ci --only=production
                npm run build
                node dist/index.js
                echo 'Deployment Done!'
